---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: calibre-web-automated
  namespace: medienmanagement
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: calibre-web-automated-secret
    template:
      data:
        HARDCOVER_TOKEN: "{{ .HARDCOVER_TOKEN }}"
  dataFrom:
    - extract:
        key: calibre-web-automated