---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: onepassword-secret
    template:
      data:
        1password-credentials.json: '{{ .OP_CREDENTIALS_JSON }}'
        token: '{{ .OP_CONNECT_TOKEN }}'
  dataFrom:
    - extract:
        key: 1password